"""Researched additions/overrides merged into build.py's T dict (source: Venice official FAQ + docs, Oct 2026)."""
X = {
"en": dict(
 lead="Venice is a generative AI platform for chat, images, video and code. It offers many open-source and premium models, shows a privacy mode on each one, and keeps your chat history in your own browser instead of on its servers.",
 f1="Privacy by design|Venice says it doesn't store or log your prompts and responses on its servers; chat history stays locally in your browser.",
 f5="Images, video & voice|Generate and edit images (upscale, enhance, Venice Studio), create video and music with credits, and use voice mode.",
 f6="Files, search & memory|Upload documents (up to 10 MB), use privacy-preserving web search and local memory; encrypted backups and share links are available.",
 privh="Privacy modes",
 priv="Venice shows a privacy mode on every model: Anonymized (your identity is hidden from the model provider, but the provider may process your prompt), Private (the default: zero-data-retention infrastructure, nothing stored), and TEE and E2EE (Pro: hardware-secured enclaves; with E2EE your prompt is encrypted on your device and only decrypted inside the enclave, but web search and memory are disabled).",
 plansh="Plans & cost",
 plans="Free: 10 text and 15 image prompts per day. Pro (listed at about $18/month): unlimited text, up to 1,000 image prompts a day, 100 monthly credits for premium features such as video, music and frontier models, plus options like removing image watermarks and the mature filter. Pro+ and Max add far more credits (7,500 and 22,500 per month). The API is billed separately. Check venice.ai/pricing for current prices.",
 refh="How my referral link works",
 ref="If you sign up through it and upgrade to Pro, both you and I get $10 in API credits (per Venice's FAQ). You can use Venice for free without upgrading.",
 knowh="Good to know",
 know="Subscriptions are generally non-refundable (cancel before renewal). Premium features consume credits. Private mode relies on commitments from Venice and its partners, and inference still runs on remote servers; use E2EE for the most sensitive work. Chat history lives in your browser, so clearing browser data deletes it unless you back it up. “Uncensored” means fewer restrictions, not no responsibility: follow the law and the terms of service.",
 q4="How does the referral link work?|If you sign up via the link and upgrade to Pro, you and the referrer each get $10 in API credits, per Venice's FAQ. Using the free tier doesn't require upgrading."),
"fa": dict(
 lead="Venice یه پلتفرم هوش مصنوعیه برای چت، تصویر، ویدیو و کدنویسی. مدل‌های متن‌باز و پرمیوم زیادی داره، روی هر مدل حالت حریم خصوصی رو نشون می‌ده و تاریخچهٔ چتت رو به‌جای سرورهاش، تو مرورگر خودت نگه می‌داره.",
 f1="حریم خصوصی از پایه|Venice می‌گه پرامپت‌ها و پاسخ‌هات رو روی سرورهاش ذخیره یا لاگ نمی‌کنه؛ تاریخچهٔ چت به‌صورت محلی تو مرورگر خودت می‌مونه.",
 f5="تصویر، ویدیو و صدا|ساخت و ویرایش تصویر (آپ‌اسکیل، Enhance، Venice Studio)، ساخت ویدیو و موسیقی با کردیت و حالت صوتی.",
 f6="فایل، جستجو و حافظه|آپلود سند (تا ۱۰ مگابایت)، جستجوی وب با حفظ حریم خصوصی و حافظهٔ محلی؛ بکاپ رمزگذاری‌شده و لینک اشتراک هم داره.",
 privh="حالت‌های حریم خصوصی",
 priv="Venice روی هر مدل یه حالت حریم خصوصی نشون می‌ده: Anonymized (هویتت از ارائه‌دهندهٔ مدل پنهان می‌مونه، ولی ممکنه اون پرامپتت رو پردازش کنه)، Private (پیش‌فرض؛ زیرساخت بدون نگهداری داده، چیزی ذخیره نمی‌شه)، و TEE و E2EE (مخصوص Pro؛ پردازش در محیط سخت‌افزاری امن، و در E2EE پرامپت روی دستگاهت رمز می‌شه و فقط داخل اون محیط باز می‌شه، ولی جستجوی وب و حافظه غیرفعاله).",
 plansh="پلن‌ها و هزینه",
 plans="رایگان: ۱۰ پرامپت متنی و ۱۵ پرامپت تصویری در روز. Pro (حدود ۱۸ دلار در ماه): متن نامحدود، تا ۱۰۰۰ پرامپت تصویری در روز، ۱۰۰ کردیت ماهانه برای امکانات ویژه مثل ویدیو، موسیقی و مدل‌های پیشرفته، و گزینه‌هایی مثل حذف واترمارک تصویر و فیلتر محتوای بزرگسال. Pro+ و Max کردیت خیلی بیشتری دارن (۷٬۵۰۰ و ۲۲٬۵۰۰ در ماه). API جدا حساب می‌شه. قیمت روز رو تو venice.ai/pricing ببین.",
 refh="لینک رفرال من چطور کار می‌کنه؟",
 ref="اگه از طریق این لینک ثبت‌نام کنی و به Pro ارتقا بدی، طبق FAQ خود Venice، هم تو و هم من ۱۰ دلار اعتبار API می‌گیریم. بدون ارتقا هم می‌تونی رایگان ازش استفاده کنی.",
 knowh="چیزهایی که باید بدونی",
 know="اشتراک‌ها معمولاً بازگشت وجه ندارن (قبل از تمدید می‌تونی لغو کنی). امکانات ویژه کردیت مصرف می‌کنن. حالت Private به تعهد Venice و شرکای زیرساختش تکیه داره و پردازش هنوز روی سرورهای راه دوره؛ برای کارهای خیلی حساس از E2EE استفاده کن. تاریخچهٔ چت تو مرورگرته، پس پاک کردن اطلاعات مرورگر اونو حذف می‌کنه مگه بکاپ بگیری. «بدون سانسور» یعنی محدودیت کمتر، نه نبود مسئولیت؛ قانون و شرایط استفاده رو رعایت کن.",
 q4="لینک رفرال چطور کار می‌کنه؟|اگه از طریق لینک ثبت‌نام کنی و به Pro ارتقا بدی، طبق FAQ خود Venice، هر دو طرف ۱۰ دلار اعتبار API می‌گیرن. استفادهٔ رایگان نیازی به ارتقا نداره."),
"ar": dict(
 lead="Venice منصة ذكاء اصطناعي توليدي للدردشة والصور والفيديو والبرمجة. توفّر نماذج مفتوحة المصدر ومتقدمة كثيرة، وتعرض وضع الخصوصية على كل نموذج، وتحتفظ بسجل محادثاتك في متصفحك بدل خوادمها.",
 f1="الخصوصية من الأساس|تقول Venice إنها لا تخزّن ولا تسجّل أوامرك وردودها على خوادمها؛ ويبقى سجل الدردشة محلياً في متصفحك.",
 f5="صور وفيديو وصوت|أنشئ الصور وعدّلها (تكبير وتحسين وVenice Studio)، وولّد فيديو وموسيقى بالرصيد، واستخدم الوضع الصوتي.",
 f6="ملفات وبحث وذاكرة|ارفع مستندات (حتى 10 ميغابايت)، وابحث في الويب مع حماية الخصوصية، واستفد من ذاكرة محلية؛ مع نسخ احتياطي مشفّر وروابط مشاركة.",
 privh="أوضاع الخصوصية",
 priv="تعرض Venice وضع الخصوصية على كل نموذج: Anonymized (تُخفى هويتك عن مزوّد النموذج لكنه قد يعالج طلبك)، وPrivate (الافتراضي؛ بنية بلا احتفاظ بالبيانات ولا يُخزَّن شيء)، وTEE وE2EE (لمشتركي Pro؛ معالجة داخل بيئة عتادية آمنة، وفي E2EE يُشفَّر طلبك على جهازك ولا يُفك إلا داخل تلك البيئة، مع تعطيل البحث في الويب والذاكرة).",
 plansh="الخطط والتكلفة",
 plans="المجانية: 10 طلبات نصية و15 طلب صورة يومياً. Pro (حوالي 18 دولاراً شهرياً): نصوص غير محدودة وحتى 1000 طلب صورة يومياً و100 رصيد شهرياً للميزات المتقدمة كالفيديو والموسيقى والنماذج المتقدمة، إضافة إلى خيارات مثل إزالة العلامة المائية للصور والفلتر الناضج. تمنح Pro+ وMax رصيداً أكبر بكثير (7,500 و22,500 شهرياً). واجهة API تُحاسَب بشكل منفصل. راجع venice.ai/pricing للأسعار الحالية.",
 refh="كيف يعمل رابط الإحالة الخاص بي؟",
 ref="إذا سجّلت عبره وترقّيت إلى Pro، فبحسب الأسئلة الشائعة لدى Venice نحصل كلانا على 10 دولارات رصيد API. ويمكنك استخدام Venice مجاناً دون الترقية.",
 knowh="أمور يجب أن تعرفها",
 know="الاشتراكات غير قابلة للاسترداد عادةً (يمكنك الإلغاء قبل التجديد). الميزات المتقدمة تستهلك الرصيد. يعتمد وضع Private على التزامات Venice وشركائها، وتتم المعالجة على خوادم بعيدة؛ استخدم E2EE للأعمال الحساسة جداً. سجل الدردشة في متصفحك، فمسح بيانات المتصفح يحذفه ما لم تنشئ نسخة احتياطية. «بلا رقابة» تعني قيوداً أقل لا غياب المسؤولية؛ التزم بالقانون وشروط الاستخدام.",
 q4="كيف يعمل رابط الإحالة؟|إذا سجّلت عبر الرابط وترقّيت إلى Pro، يحصل الطرفان على 10 دولارات رصيد API بحسب الأسئلة الشائعة لدى Venice. الاستخدام المجاني لا يتطلب ترقية."),
"tr": dict(
 lead="Venice; sohbet, görsel, video ve kodlama için üretken bir yapay zekâ platformu. Çok sayıda açık kaynak ve premium model sunar, her modelde gizlilik modunu gösterir ve sohbet geçmişinizi sunucuları yerine tarayıcınızda tutar.",
 f1="Tasarımdan gelen gizlilik|Venice, istemlerinizi ve yanıtlarınızı sunucularında saklamadığını veya kaydetmediğini belirtiyor; sohbet geçmişi yerel olarak tarayıcınızda kalır.",
 f5="Görsel, video ve ses|Görsel üretin ve düzenleyin (büyütme, iyileştirme, Venice Studio), kredilerle video ve müzik oluşturun, sesli modu kullanın.",
 f6="Dosya, arama ve hafıza|Belge yükleyin (10 MB'a kadar), gizliliği koruyan web aramasını ve yerel hafızayı kullanın; şifreli yedek ve paylaşım bağlantıları da var.",
 privh="Gizlilik modları",
 priv="Venice her modelde bir gizlilik modu gösterir: Anonymized (kimliğiniz model sağlayıcıdan gizlenir ancak sağlayıcı isteminizi işleyebilir), Private (varsayılan; veri saklamayan altyapı, hiçbir şey saklanmaz), TEE ve E2EE (Pro; donanımla güvenli ortamda işlem. E2EE'de istem cihazınızda şifrelenir ve yalnızca o ortamda çözülür, ancak web araması ve hafıza devre dışıdır).",
 plansh="Planlar ve maliyet",
 plans="Ücretsiz: günde 10 metin ve 15 görsel istemi. Pro (yaklaşık 18 $/ay): sınırsız metin, günde 1.000'e kadar görsel istemi, video, müzik ve gelişmiş modeller gibi premium özellikler için aylık 100 kredi; ayrıca görsel filigranını ve yetişkin filtresini kapatma seçenekleri. Pro+ ve Max çok daha fazla kredi verir (aylık 7.500 ve 22.500). API ayrı faturalandırılır. Güncel fiyatlar için venice.ai/pricing adresine bakın.",
 refh="Referans bağlantım nasıl çalışıyor?",
 ref="Bu bağlantıyla kaydolup Pro'ya yükseltirseniz, Venice'in SSS'sine göre hem siz hem ben 10 $ API kredisi alırız. Yükseltmeden de Venice'i ücretsiz kullanabilirsiniz.",
 knowh="Bilmeniz gerekenler",
 know="Abonelikler genellikle iade edilmez (yenilemeden önce iptal edebilirsiniz). Premium özellikler kredi tüketir. Private mod, Venice ve ortaklarının taahhütlerine dayanır; işlem yine uzak sunucularda yapılır, çok hassas işler için E2EE kullanın. Sohbet geçmişi tarayıcınızdadır; tarayıcı verilerini silmek, yedek almadıysanız onu da siler. «Sansürsüz», daha az kısıtlama demektir, sorumluluksuzluk değil; yasalara ve kullanım koşullarına uyun.",
 q4="Referans bağlantısı nasıl çalışır?|Bağlantıyla kaydolup Pro'ya yükseltirseniz, Venice'in SSS'sine göre iki taraf da 10 $ API kredisi alır. Ücretsiz kullanım için yükseltme gerekmez."),
"ru": dict(
 lead="Venice — платформа генеративного ИИ для чата, изображений, видео и кода. В ней много открытых и премиальных моделей, у каждой показан режим приватности, а история чата хранится в вашем браузере, а не на её серверах.",
 f1="Приватность по умолчанию|Venice заявляет, что не хранит и не логирует ваши запросы и ответы на своих серверах; история чата остаётся локально в браузере.",
 f5="Изображения, видео и голос|Создание и редактирование изображений (апскейл, Enhance, Venice Studio), видео и музыка за кредиты, голосовой режим.",
 f6="Файлы, поиск и память|Загрузка документов (до 10 МБ), веб-поиск с сохранением приватности, локальная память; есть зашифрованные бэкапы и ссылки для обмена.",
 privh="Режимы приватности",
 priv="У каждой модели показан режим приватности: Anonymized (ваша личность скрыта от провайдера модели, но он может обработать запрос), Private (по умолчанию; инфраструктура без хранения данных, ничего не сохраняется), TEE и E2EE (Pro; обработка в аппаратно защищённой среде, а в E2EE запрос шифруется на вашем устройстве и расшифровывается только внутри неё, но веб-поиск и память отключены).",
 plansh="Тарифы и стоимость",
 plans="Бесплатно: 10 текстовых и 15 графических запросов в день. Pro (около 18 $/мес): безлимитный текст, до 1000 запросов изображений в день, 100 кредитов в месяц на премиум-функции (видео, музыка, продвинутые модели), а также отключение водяного знака и фильтра 18+. Pro+ и Max дают намного больше кредитов (7 500 и 22 500 в месяц). API оплачивается отдельно. Актуальные цены — на venice.ai/pricing.",
 refh="Как работает моя реферальная ссылка?",
 ref="Если вы зарегистрируетесь по ней и перейдёте на Pro, то, согласно FAQ Venice, и вы, и я получим по 10 $ кредитов API. Пользоваться бесплатно можно и без апгрейда.",
 knowh="Что нужно знать",
 know="Подписки, как правило, не возвращаются (отменить можно до продления). Премиум-функции расходуют кредиты. Режим Private опирается на обязательства Venice и партнёров, а обработка всё равно идёт на удалённых серверах — для самых чувствительных задач используйте E2EE. История чата хранится в браузере, поэтому очистка данных браузера удалит её, если нет бэкапа. «Без цензуры» значит меньше ограничений, а не отсутствие ответственности; соблюдайте закон и условия использования.",
 q4="Как работает реферальная ссылка?|Если зарегистрироваться по ссылке и перейти на Pro, обе стороны, по FAQ Venice, получают по 10 $ кредитов API. Для бесплатного использования апгрейд не нужен."),
}
